GET http://localhost:3000/companies

###

POST http://localhost:3000/companies
Content-Type: application/json

{
  "name": "Yandex",
  "domain": "www.google.com",
  "description": "Search Engine App"
}
